#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libffi-soname6
Version  : 3.2.1
Release  : 41
URL      : https://github.com/libffi/libffi/archive/v3.2.1/libffi-3.2.1.tar.gz
Source0  : https://github.com/libffi/libffi/archive/v3.2.1/libffi-3.2.1.tar.gz
Summary  : Library supporting Foreign Function Interfaces
Group    : Development/Tools
License  : LGPL-2.0+
Requires: compat-libffi-soname6-lib = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : tcl
BuildRequires : texinfo
Patch1: 0001-Update-ax_cc_maxopt.m4-macro-for-libffi-3.2.1.patch

%description
Status
======
libffi-3.2.1 was released on November 12, 2014.  Check the libffi web
page for updates: <URL:http://sourceware.org/libffi/>.

%package lib
Summary: lib components for the compat-libffi-soname6 package.
Group: Libraries

%description lib
lib components for the compat-libffi-soname6 package.


%package lib32
Summary: lib32 components for the compat-libffi-soname6 package.
Group: Default

%description lib32
lib32 components for the compat-libffi-soname6 package.


%prep
%setup -q -n libffi-3.2.1
cd %{_builddir}/libffi-3.2.1
%patch1 -p1
pushd ..
cp -a libffi-3.2.1 build32
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617128932
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fuse-ld=bfd -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_GEN"
export FCFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fuse-ld=bfd -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_GEN"
export FFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fuse-ld=bfd -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fuse-ld=bfd -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_GEN"
export LDFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fuse-ld=bfd -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_GEN"
#
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -malign-data=cacheline -feliminate-unused-debug-types -fno-lto -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_USE"
export FCFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -malign-data=cacheline -feliminate-unused-debug-types -fno-lto -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_USE"
export FFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -malign-data=cacheline -feliminate-unused-debug-types -fno-lto -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_USE"
export CXXFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -malign-data=cacheline -feliminate-unused-debug-types -fno-lto -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -fvisibility-inlines-hidden -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_USE"
export LDFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -malign-data=cacheline -feliminate-unused-debug-types -fno-lto -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -pipe  -fPIC -fipa-pta -flto=16 -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -Wl,-O2 -Wl,-z,now -Wl,-z,relro -ffat-lto-objects -fomit-frame-pointer -ffast-math -fstrict-aliasing -fexceptions $PGO_USE"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
%global _lto_cflags 1
## altflags_pgo end
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%autogen --enable-shared --enable-static --disable-docs --enable-portable-binary --without-gcc-arch
make  %{?_smp_mflags}  V=1 VERBOSE=1

make VERBOSE=1 V=1 %{?_smp_mflags} check || :
make clean
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%autogen
make  %{?_smp_mflags}  V=1 VERBOSE=1

pushd ../build32/
## altflags1_32 content
export CFLAGS="-O3 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native -fexceptions -fomit-frame-pointer -fstrict-aliasing -ffast-math"
export CXXFLAGS="-O3 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native -fexceptions -fomit-frame-pointer -fstrict-aliasing -ffast-math"
export LDFLAGS="-O3 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native -fexceptions -fomit-frame-pointer -fstrict-aliasing -ffast-math"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#
## altflags1_32 end
%autogen --disable-static --enable-shared --enable-static --disable-docs --enable-portable-binary --without-gcc-arch  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}  V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1617128932
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/lib32/libffi-3.2.1/include/ffi.h
rm -f %{buildroot}/usr/lib32/libffi-3.2.1/include/ffitarget.h
rm -f %{buildroot}/usr/lib32/libffi.so
rm -f %{buildroot}/usr/lib32/pkgconfig/32libffi.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/libffi.pc
rm -f %{buildroot}/usr/lib64/libffi-3.2.1/include/ffi.h
rm -f %{buildroot}/usr/lib64/libffi-3.2.1/include/ffitarget.h
rm -f %{buildroot}/usr/lib64/libffi.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libffi.pc
rm -f %{buildroot}/usr/share/info/libffi.info
rm -f %{buildroot}/usr/share/man/man3/ffi.3
rm -f %{buildroot}/usr/share/man/man3/ffi_call.3
rm -f %{buildroot}/usr/share/man/man3/ffi_prep_cif.3
rm -f %{buildroot}/usr/share/man/man3/ffi_prep_cif_var.3

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libffi.so.6
/usr/lib64/libffi.so.6.0.4

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libffi.so.6
/usr/lib32/libffi.so.6.0.4
